resources:
  repositories:
    - repository: self
      type: git
      ref: main
jobs:
  - job: Job_1
    displayName: Psotman-newman
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        clean: true
      - task: Npm@1
        displayName: npm custom
        inputs:
          command: custom
          workingDir: postman
          verbose: false
          customCommand: install newman -g
      - task: NodeAndNpmTool@1
        displayName: Use Node 16.9.0
        inputs:
          versionSpec: 16.9.0
      - task: Npm@1
        displayName: install html report
        inputs:
          command: custom
          workingDir: postman
          verbose: false
          customCommand: install -g newman-reporter-htmlextra
      - task: CmdLine@2
        displayName: Run Test With Report
        inputs:
          script: >+
            - script: |
                    sudo npm install -g newman

                    sudo npm install -g newman-reporter-junitfull
                  displayName: 'Install Postman Dependencies'
            - script:
                    newman run "$(System.DefaultWorkingDirectory)/postman/udacity_postmanAPI.postman_collection.json" -e "$(System.DefaultWorkingDirectory)/postman/udacity_postman_env.postman_environment.json"  -r cli,junitfull --reporter-junitfull-export Results\junitReport.xml


      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFiles: "**/*.xml"
          searchFolder: '$(System.DefaultWorkingDirectory)/postman/Results\*.xml '

      - task: PublishTestResults@2
        displayName: "Publish Test Results **/newman-run-report-*.xml"
        condition: always()
        inputs:
          testRunTitle: "Regression Tests"
          testResultsFiles: "**/newman-run-report-*.xml"
