variables:
  system.debug: true

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Stage
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
          - task: PublishPipelineArtifact@1
            displayName: "Publish Terraform Code"
            inputs:
              path: "$(system.DefaultWorkingDirectory)/selenium"
              artifact: SeleniumBuild
  - stage: DownloadArtifact
    displayName: "Download Selenium"
    jobs:
      - job: Build
        displayName: DownloadCode
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: SeleniumBuild
              buildVersionToDownload: latest
              downloadPath: $(system.DefaultWorkingDirectory)

  - stage: deploy
    displayName: Deploy to TST
    jobs:
      - job: deploy
        pool:
          name: Hosted Ubuntu 1604
        steps:
          # Needed for Terraform VM deployment
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: "1rZQRrKIsqI8hamFMlXlgcPcWnjB7hsF2Z1N3S2yMIT6JW6mN31g08nn8gt5onw+LMG9uhkRRToC6vUZbkZo590aVv5kTNQWLY0l+gkr05oNX94e/w== azureuser@myserver"
              sshPublicKey: "$(system.DefaultWorkingDirectory)/terraform-manifests/ssh-keys/terraform-azure.pub"
              sshKeySecureFile: terraform-azure.pem

  - stage: DeployTst
    displayName: Deploy to TST
    jobs:
      - deployment: Deployment
        environment:
          name: udacity
        name:
        resourceType: VirtualMachine
        tags: Ubuntu
        strategy:
        runOnce:
          deploy:
            steps:
              steps:
                - task: UsePythonVersion@0
                  displayName: "Use Python 3.8"
                  inputs:
                    versionSpec: 3.8
                - script: |
                    python -m pip install --upgrade pip
                    sudo apt-get upgrade -y
                    sudo apt-get install python3-pip -y
                    sudo apt-get install unzip -y
                    sudo apt-get install -y chromium-browser
                    pip3 install selenium
                    pip install pytest
                    pip install pytest-html
                    pip install chromedriver-py==88.0.4324.96
                    pip install pytest-xdist
                    pip install pytest-nunit
                    sudo apt install google-chrome-stable
                    pip install webdriver_manager
                - task: Bash@3
                  displayName: "Install Plugins"
                  inputs:
                    versionSpec: 3.8
                - script: |
                    sudo rm -rf chromedriver*
                    wget https://chromedriver.storage.googleapis.com/<version>/chromedriver_linux64.zip //update the version here
                    unzip chromedriver*.zip
                    sudo mv chromedriver -f /usr/bin
                    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml || true

                - task: PublishPipelineArtifact@1
                  displayName: "Publish Pipeline Artifact"
                  inputs:
                    artifact: "Test_reports"
                - task: PublishTestResults@2
                  displayName: "Publish Test Results"
                  inputs:
                    testResultsFormat: NUnit
                    testResultsFiles: "**/*-results.xml"
                - task: LakshayKaushik.PublishHTMLReports.publishhtmlreport.publishhtmlreport@1
                  displayName: "publish html report"
                  inputs:
                    htmlType: "HTML-Report"
                - task: PublishTestResults@2
                  displayName: "Publish Integration Test"
                  inputs:
                    testResultsFormat: "JUnit"
                    testResultsFiles: "result*.xml"
                    mergeTestResults: true
                    testRunTitle: "Publish Test Results"
